on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  bytebase-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Bytebase
        id: bytebase-login
        uses: bytebase/login-action@main
        with:
          bytebase-url: ${{ secrets.BYTEBASE_URL }}
          service-key: ${{ secrets.BYTEBASE_SERVICE_KEY }}
          service-secret: ${{ secrets.BYTEBASE_SERVICE_SECRET }}
      - name: Debug API URL
        run: |
          echo "API URL Length: $(echo -n "${{ steps.bytebase-login.outputs.api_url }}" | wc -c)"
          echo "Token Length: $(echo -n "${{ steps.bytebase-login.outputs.token }}" | wc -c)"
      - name: List projects
        run: |
          curl "${{ steps.bytebase-login.outputs.api_url }}/v1/projects" \
            -H "Authorization: Bearer ${{ steps.bytebase-login.outputs.token }}" \
            -H 'Content-Type: application/json; charset=utf-8'